### PR TITLE
Ruby 3 support

### PR DESCRIPTION
**Pull request by honzasterba**
I have taken the changes from https://github.com/matthewrudy/memoist/pull/92 fixed up the code and added tests and CI runs for Ruby 3 and 3.1

The solution for ruby3 kwargs is to add the hash of passed kwargs in its array form the the cache ivar.

### CODE REVIEW

**Review by bkeepers — APPROVED** [review]
👍 These changes look good to me. Hopefully it gets merged soon.

**Comment by patbl** [comment]
It probably won't be merged soon: https://github.com/matthewrudy/memoist/issues/88#issuecomment-918506434

**Comment by evanbattaglia** [comment]
Thanks for doing this! Maybe we should make this against https://github.com/memoist/memoist ? Or possibly @sebjacobs would be able to approve this?

**Comment by honzasterba** [comment]
@evanbattaglia moved to https://github.com/memoist/memoist/pull/2

**Comment by pboling** [comment]
FYI: Added this alert to the new repo

> [!IMPORTANT]
>
> # Recommendation
>
> Consider using [MemoWise](https://github.com/panorama-ed/memo_wise) instead, as it is maintained, fully tested, provides thread safety guarantees, and is much, much faster.
>
> # Other Alternatives
>
> In case you need a tool with this feature set that is currently maintained, check out:
> * https://github.com/makandra/memoized
> * https://github.com/honzasterba/memoist
> * https://github.com/tycooon/memery

> [!TIP]  
> Seriously though, read the important note above.

> [!WARNING]  
> If you must continue - be aware that this is unmaintained software.

**Pull request closed without merging**
